'use client';

import {artifactTypes,definitions,newArtifact,type ArtifactRecord,type ArtifactType} from '../../lib/archive/model';
import {isAudioAsset,publicAssetUrl} from '../../lib/studio/assets';
import {useStudio} from './StudioProvider';

export function AddArtifact({onAdd}:{onAdd:(a:ArtifactRecord)=>void}){
 return <select aria-label="Add artifact" value="" onChange={event=>onAdd(newArtifact(event.target.value as ArtifactType))}><option value="" disabled>Add artifact…</option>{artifactTypes.map(type=><option key={type}>{type}</option>)}</select>;
}

export default function ArtifactInspector({artifact:a,onChange,onDuplicate,onDelete}:{artifact:ArtifactRecord;onChange:(a:ArtifactRecord)=>void;onDuplicate:()=>void;onDelete:()=>void}){
 const {assets,checkpoint}=useStudio(),definition=definitions[a.type];
 const imageAssets=assets.filter(asset=>!isAudioAsset(asset));
 const audioAssets=assets.filter(asset=>isAudioAsset(asset)&&asset.approved);
 const change=(patch:Partial<ArtifactRecord>)=>{checkpoint();onChange({...a,...patch})};
 const contentField=(field:string)=>{
  if(field==='intro') return <textarea rows={8} value={a.content[field]||''} onChange={event=>change({content:{...a.content,[field]:event.target.value}})}/>;
  if(field==='audio') return <select aria-label="Audio asset" value={a.content.audio||''} onChange={event=>change({content:{...a.content,audio:event.target.value}})}><option value="">Select approved MP3…</option>{a.content.audio&&!audioAssets.some(asset=>publicAssetUrl(asset.storage_path)===a.content.audio)&&<option value={a.content.audio}>Current URL</option>}{audioAssets.map(asset=><option key={asset.id} value={publicAssetUrl(asset.storage_path)}>{asset.name}</option>)}</select>;
  return <input value={a.content[field]||''} onChange={event=>change({...(field==='image'?{asset_id:null}:{}),content:{...a.content,[field]:event.target.value}})}/>;
 };
 const selectCardAsset=(side:'front'|'back')=>{
  const idKey=`${side}_asset_id`,imageKey=`${side}_image`,altKey=`${side}_alt`;
  return <label>{side==='front'?'Front asset':'Back asset'}<select value={a.content[idKey]||''} onChange={event=>{const asset=imageAssets.find(item=>item.id===event.target.value);change({...(side==='front'?{asset_id:asset?.id||null}:{}),content:{...a.content,[idKey]:asset?.id||'',[imageKey]:asset?publicAssetUrl(asset.storage_path):'',[altKey]:asset?.alt_text||''}})}}><option value="">Select image…</option>{imageAssets.map(asset=><option key={asset.id} value={asset.id}>{asset.name}{asset.approved?'':' (private)'}</option>)}</select></label>;
 };

 return <aside className="studio-inspector"><h2>{a.type}</h2><label>Name<input value={a.name} onChange={event=>change({name:event.target.value})}/></label><p className="studio-muted">{a.key}</p><label><input type="checkbox" checked={a.locked} onChange={event=>change({locked:event.target.checked})}/>Locked</label><label><input type="checkbox" checked={a.visible} onChange={event=>change({visible:event.target.checked})}/>Visible</label><fieldset disabled={a.locked}><legend>Layout</legend><div className="studio-properties">{(['x','y','width','height','rotate','z'] as const).map(key=><label key={key}>{key}<input type="number" step={key==='z'?1:'any'} value={a[key]??''} placeholder={key==='height'?'Auto':''} onFocus={checkpoint} onChange={event=>onChange({...a,[key]:key==='height'&&event.target.value===''?null:Number(event.target.value)})}/></label>)}</div>{a.type==='card'?<><fieldset className="studio-card-fields"><legend>Card faces</legend>{selectCardAsset('front')}{selectCardAsset('back')}<label>Front alt text<input value={a.content.front_alt||''} onChange={event=>change({content:{...a.content,front_alt:event.target.value}})}/></label><label>Back alt text<input value={a.content.back_alt||''} onChange={event=>change({content:{...a.content,back_alt:event.target.value}})}/></label><label>Flip duration (ms)<input type="number" min={100} max={2000} value={a.config.duration??680} onChange={event=>change({config:{...a.config,duration:Number(event.target.value)}})}/></label></fieldset></>:<><label>Asset<select value={a.asset_id||''} onChange={event=>{const asset=imageAssets.find(item=>item.id===event.target.value);change({asset_id:asset?.id||null,content:{...a.content,image:asset?publicAssetUrl(asset.storage_path):a.content.image}})}}><option value="">Local / custom path</option>{imageAssets.map(asset=><option key={asset.id} value={asset.id}>{asset.name}{asset.approved?'':' (private)'}</option>)}</select></label>{definition.fields.map(field=><label key={field}>{field}{contentField(field)}</label>)}<label>Hover<select value={a.animation} onChange={event=>change({animation:event.target.value as ArtifactRecord['animation']})}>{definition.animations.map(value=><option key={value}>{value}</option>)}</select></label>{a.animation==='lift'&&<><label>Lift (px)<input type="number" min={0} max={30} value={a.config.lift??8} onChange={event=>change({config:{...a.config,lift:Number(event.target.value)}})}/></label><label>Duration (ms)<input type="number" min={100} max={2000} value={a.config.duration??500} onChange={event=>change({config:{...a.config,duration:Number(event.target.value)}})}/></label></>}</>}<label>Click<select value={a.action} onChange={event=>change({action:event.target.value as ArtifactRecord['action']})}>{definition.actions.map(value=><option key={value}>{value}</option>)}</select></label><button onClick={onDuplicate}>Duplicate</button> <button onClick={onDelete}>Delete</button></fieldset></aside>;
}
