'use client';
import {artifactTypes,definitions,newArtifact,type ArtifactRecord,type ArtifactType} from '../../lib/archive/model';
import {isAudioAsset,publicAssetUrl} from '../../lib/studio/assets';
import {useStudio} from './StudioProvider';

export function AddArtifact({onAdd}:{onAdd:(a:ArtifactRecord)=>void}){return <select aria-label="Add artifact" value="" onChange={e=>onAdd(newArtifact(e.target.value as ArtifactType))}><option value="" disabled>Add artifact…</option>{artifactTypes.map(t=><option key={t}>{t}</option>)}</select>}

export default function ArtifactInspector({artifact:a,onChange,onDuplicate,onDelete}:{artifact:ArtifactRecord;onChange:(a:ArtifactRecord)=>void;onDuplicate:()=>void;onDelete:()=>void}){
 const {assets,checkpoint}=useStudio(),d=definitions[a.type];
 const imageAssets=assets.filter(item=>!isAudioAsset(item));
 const audioAssets=assets.filter(item=>isAudioAsset(item)&&item.approved);
 const change=(patch:Partial<ArtifactRecord>)=>{checkpoint();onChange({...a,...patch})};
 const contentField=(field:string)=>{
  if(field==='intro') return <textarea rows={8} value={a.content[field]||''} onChange={e=>change({content:{...a.content,[field]:e.target.value}})}/>;
  if(field==='audio') return <select aria-label="Audio asset" value={a.content.audio||''} onChange={e=>change({content:{...a.content,audio:e.target.value}})}><option value="">Select approved MP3…</option>{a.content.audio&&!audioAssets.some(asset=>publicAssetUrl(asset.storage_path)===a.content.audio)&&<option value={a.content.audio}>Current URL</option>}{audioAssets.map(asset=><option key={asset.id} value={publicAssetUrl(asset.storage_path)}>{asset.name}</option>)}</select>;
  return <input value={a.content[field]||''} onChange={e=>change({...(field==='image'?{asset_id:null}:{}),content:{...a.content,[field]:e.target.value}})}/>;
 };
 return <aside className="studio-inspector"><h2>{a.type}</h2><label>Name<input value={a.name} onChange={e=>change({name:e.target.value})}/></label><p className="studio-muted">{a.key}</p><label><input type="checkbox" checked={a.locked} onChange={e=>change({locked:e.target.checked})}/>Locked</label><label><input type="checkbox" checked={a.visible} onChange={e=>change({visible:e.target.checked})}/>Visible</label><fieldset disabled={a.locked}><legend>Layout</legend><div className="studio-properties">{(['x','y','width','height','rotate','z'] as const).map(key=><label key={key}>{key}<input type="number" step={key==='z'?1:'any'} value={a[key]??''} placeholder={key==='height'?'Auto':''} onFocus={checkpoint} onChange={e=>onChange({...a,[key]:key==='height'&&e.target.value===''?null:Number(e.target.value)})}/></label>)}</div><label>Asset<select value={a.asset_id||''} onChange={e=>{const asset=imageAssets.find(item=>item.id===e.target.value);change({asset_id:asset?.id||null,content:{...a.content,image:asset?publicAssetUrl(asset.storage_path):a.content.image}})}}><option value="">Local / custom path</option>{imageAssets.map(asset=><option key={asset.id} value={asset.id}>{asset.name}{asset.approved?'':' (private)'}</option>)}</select></label>{d.fields.map(field=><label key={field}>{field}{contentField(field)}</label>)}<label>Hover<select value={a.animation} onChange={e=>change({animation:e.target.value as ArtifactRecord['animation']})}>{d.animations.map(value=><option key={value}>{value}</option>)}</select></label>{a.animation==='lift'&&<><label>Lift (px)<input type="number" min={0} max={30} value={a.config.lift??8} onChange={e=>change({config:{...a.config,lift:Number(e.target.value)}})}/></label><label>Duration (ms)<input type="number" min={100} max={2000} value={a.config.duration??500} onChange={e=>change({config:{...a.config,duration:Number(e.target.value)}})}/></label></>}<label>Click<select value={a.action} onChange={e=>change({action:e.target.value as ArtifactRecord['action']})}>{d.actions.map(value=><option key={value}>{value}</option>)}</select></label><button onClick={onDuplicate}>Duplicate</button> <button onClick={onDelete}>Delete</button></fieldset></aside>;
}
