'use client';
/* eslint-disable @next/next/no-img-element -- Approved public Storage assets are rendered directly. */
import {useMemo,useState} from 'react';
import {useStudio} from './StudioProvider';
import {publicAssetUrl} from '../../lib/studio/assets';
import type {GalleryItem,PuzzleItem} from '../../lib/archive/collections';
import galleryFallback from '../../data/photo-manifest.json';
import puzzleFallback from '../../data/puzzle-manifest.json';

type Kind='gallery'|'puzzle';
export default function CollectionEditor({kind}:{kind:Kind}){
 const s=useStudio(),[assetId,setAssetId]=useState(''),[preview,setPreview]=useState(false);const items=s.collections[kind];
 const approved=useMemo(()=>s.assets.filter(asset=>asset.approved&&asset.mime_type.startsWith('image/')&&!items.some(item=>item.asset_id===asset.id)),[s.assets,items]);
 const assetMap=useMemo(()=>new Map(s.assets.map(asset=>[asset.id,asset])),[s.assets]);
 const commit=(next:(GalleryItem|PuzzleItem)[])=>s.setCollections({...s.collections,[kind]:next.map((item,index)=>({...item,sort_order:index}))});
 const add=()=>{const asset=assetMap.get(assetId);if(!asset||!asset.approved)return;const base={id:crypto.randomUUID(),asset_id:asset.id,title:asset.name.replace(/\.[^.]+$/,''),alt_text:asset.alt_text,sort_order:items.length,visible:true};commit([...items,kind==='gallery'?{...base,caption:'',location:'',year:''}:base] as (GalleryItem|PuzzleItem)[]);setAssetId('')};
 const importFallback=()=>{const fallback=kind==='gallery'?galleryFallback:puzzleFallback;const existing=new Set(items.map(item=>item.asset_id));const additions=fallback.flatMap((entry,index)=>{const asset=s.assets.find(candidate=>candidate.approved&&candidate.source_path?.toLowerCase()===entry.src.toLowerCase());if(!asset||existing.has(asset.id))return[];const base={id:crypto.randomUUID(),asset_id:asset.id,title:entry.title,alt_text:asset.alt_text||('caption'in entry?entry.caption:entry.title),sort_order:items.length+index,visible:true};return[kind==='gallery'?{...base,caption:'caption'in entry?entry.caption:'',location:'',year:'year'in entry?entry.year:''}:base]});commit([...items,...additions] as (GalleryItem|PuzzleItem)[]);s.setStatus(`Added ${additions.length} approved local ${kind} assets to the collection draft.`)};
 const change=(id:string,patch:Record<string,string|boolean>)=>commit(items.map(item=>item.id===id?{...item,...patch}:item));
 const move=(index:number,delta:number)=>{const target=index+delta;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];commit(next)};
 return <main className="studio-page studio-collection-page"><header className="studio-collection-header"><div><h1>{kind==='gallery'?'Gallery':'Puzzle'}</h1><p>Draft changes stay private until both collections are published.</p></div><div><button onClick={()=>setPreview(value=>!value)}>{preview?'Edit collection':'Preview'}</button><button onClick={()=>void s.saveCollections().catch(error=>s.setStatus(error.message))}>Save Draft</button><button onClick={()=>{if(window.confirm('Publish the current Gallery and Puzzle drafts?'))void s.publishCollections().catch(error=>s.setStatus(error.message))}}>Publish Collections</button></div></header>
  <div className="studio-collection-add"><select aria-label={`Approved asset for ${kind}`} value={assetId} onChange={event=>setAssetId(event.target.value)}><option value="">Choose approved image</option>{approved.map(asset=><option key={asset.id} value={asset.id}>{asset.name}</option>)}</select><button disabled={!assetId} onClick={add}>Add asset</button><button onClick={importFallback}>Import approved local fallback</button></div>
  {preview?<div className={`studio-collection-preview ${kind}`}>{items.filter(item=>item.visible).map(item=>{const asset=assetMap.get(item.asset_id);return asset?<figure key={item.id}><img src={publicAssetUrl(asset.storage_path)} alt={item.alt_text}/><figcaption><strong>{item.title}</strong>{kind==='gallery'&&<span>{(item as GalleryItem).caption}</span>}</figcaption></figure>:null})}</div>:<div className="studio-collection-list">{items.map((item,index)=>{const asset=assetMap.get(item.asset_id);return <article key={item.id}><img src={asset?publicAssetUrl(asset.storage_path):undefined} alt=""/><div className="studio-collection-fields"><label>Title<input value={item.title} onChange={event=>change(item.id,{title:event.target.value})}/></label><label>Alt text<input value={item.alt_text} onChange={event=>change(item.id,{alt_text:event.target.value})}/></label>{kind==='gallery'&&<><label>Caption<input value={(item as GalleryItem).caption} onChange={event=>change(item.id,{caption:event.target.value})}/></label><label>Location<input value={(item as GalleryItem).location} onChange={event=>change(item.id,{location:event.target.value})}/></label><label>Year<input value={(item as GalleryItem).year} onChange={event=>change(item.id,{year:event.target.value})}/></label></>}<label className="studio-check"><input type="checkbox" checked={item.visible} onChange={event=>change(item.id,{visible:event.target.checked})}/>Visible</label></div><div className="studio-collection-actions"><button disabled={index===0} onClick={()=>move(index,-1)}>Move up</button><button disabled={index===items.length-1} onClick={()=>move(index,1)}>Move down</button><button onClick={()=>commit(items.filter(candidate=>candidate.id!==item.id))}>Remove</button></div></article>})}</div>}
 </main>;
}
